# Generated by Django 6.0.2 on 2026-03-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_teacher_grade_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MFS', 'Mobile Financial Service (bkash/Nagad)'), ('Bank', 'Bank Transfer')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students_app.student'),
        ),
    ]
