# Generated by Django 6.0.2 on 2026-03-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_alter_attendance_options_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('slot_number', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.grade')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.teacher')),
            ],
            options={
                'unique_together': {('grade', 'day', 'slot_number')},
            },
        ),
    ]
